# Update <REGISTRY> <NAMESPACE> values before use
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdots11
  labels:
    app: cdots11
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cdots11
  template:
    metadata:
      labels:
        app: cdots11
    spec:
      containers:
      - name: cdots11
        image: us.icr.io/cdots/cdots:latest
        ports:
        - containerPort: 8000
        imagePullPolicy: Always
        env:
        - name: CLOUDANT_URL
          valueFrom:
            secretKeyRef:
              name: cloudant
              key: url
              optional: true
        - name: CLOUDANT_USERNAME
          valueFrom:
            secretKeyRef:
              name: cloudant
              key: username
              optional: true
        - name: CLOUDANT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudant
              key: password
              optional: true

